# Generated by Django 2.2.1 on 2019-11-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('Post', 'Post'), ('Soru', 'Soru')], max_length=20)),
                ('category', models.CharField(choices=[('Aşk', 'Aşk'), ('Dost Kazığı', 'Dost Kazığı'), ('Avcılar', 'Avcılar'), ('Civcivler', 'Civcivler'), ('Profesyonellik içerenler', 'Profesyonellik içerenler'), ('Diğer', 'Diğer')], max_length=20)),
                ('publish_date', models.DateField()),
                ('content', models.CharField(max_length=2000)),
                ('likecount', models.IntegerField()),
                ('replycount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Mühendislik', 'Mühendislik'), ('Mimarlık', 'Mimarlık'), ('Fen-Edebiyat', 'Fen-Edebiyat'), ('İktisadi-İdari', 'İktisadi-İdari'), ('Güzel Sanatlar', 'Güzel Sanatlar')], max_length=20)),
                ('birthdate', models.DateField()),
                ('createdat', models.DateField()),
                ('postCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.User')),
                ('isAdmin', models.BooleanField(default=True)),
            ],
            bases=('website.user',),
        ),
        migrations.CreateModel(
            name='Post_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='publish_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
        migrations.CreateModel(
            name='Follower_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_list_followed_by', to='website.User')),
                ('followingto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_list_following_to', to='website.User')),
            ],
        ),
        migrations.CreateModel(
            name='reply_Post',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Post')),
                ('main_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_post_main_post', to='website.Post')),
                ('replied_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_post_replied_post', to='website.Post')),
            ],
            bases=('website.post',),
        ),
    ]
