# Generated by Django 2.2.1 on 2019-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(choices=[('Mühendislik', 'Mühendislik'), ('Mimarlık', 'Mimarlık'), ('Fen-Edebiyat', 'Fen-Edebiyat'), ('İktisadi-İdari', 'İktisadi-İdari'), ('Güzel Sanatlar', 'Güzel Sanatlar')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Post_List',
        ),
    ]
