# Generated by Django 2.2.1 on 2020-01-06 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_auto_20200106_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likecount',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Liked_Post',
        ),
    ]
