# Generated by Django 2.2.1 on 2020-01-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200106_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower_list',
            name='followedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_list_followed_by', to='website.UserProfile'),
        ),
        migrations.AlterField(
            model_name='follower_list',
            name='followingto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_list_following_to', to='website.UserProfile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserProfile'),
        ),
    ]
