# Generated by Django 2.2.1 on 2020-01-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_userprofile_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='followers',
            new_name='following',
        ),
    ]
