# Generated by Django 2.2.1 on 2020-01-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200106_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Aşk', 'Aşk'), ('Dost Kazığı', 'Dost Kazığı'), ('Avcılar', 'Avcılar'), ('Civcivler', 'Civcivler'), ('Profesyonellik içerenler', 'Profesyonellik içerenler'), ('Diğer', 'Diğer')], max_length=50),
        ),
    ]
