# Generated by Django 2.2.1 on 2020-01-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200112_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
